version: '3.3'
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'production'
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - database-pg:/var/lib/postgresql/data
        
  api:
    build:
      context: .
      dockerfile: backend/backend/Dockerfile
    networks:
      - backend
    ports:
        - "8080:80"
    depends_on:
      - database
      - nginx
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 1024M
        
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      - backend
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      
networks:
  backend:
    driver: bridge

volumes:
  database-pg: